### ISSUE TITLE
关于部署 容器CloudSim 所需的硬件配置

### ISSUE THREAD

**Issue by AbstractWorld** [diewenhua/ContainerCloudSim#2]
你好，我在阅读一篇论文时看到了ContainerCloudSim仿真平台，请问部署这个平台是否需要较高的硬件配置？这个平台有无更详细的使用文档或软件架构图？谢谢解答。

**Comment by diewenhua** [comment]
你好，这个不需要太高的配置的，一般的电脑就行。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "diewenhua/ContainerCloudSim"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月7日(星期天) 晚上8:31
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[diewenhua/ContainerCloudSim] 关于部署 容器CloudSim 所需的硬件配置 (Issue #2)





 
你好，我在阅读一篇论文时看到了ContainerCloudSim仿真平台，请问部署这个平台是否需要较高的硬件配置？这个平台有无更详细的使用文档或软件架构图？谢谢解答。
